# Use the official Node.js image
FROM node:18-slim

# Set the working directory
WORKDIR /usr/src/app

# Install application dependencies
COPY package*.json ./
RUN npm install

# Copy the application source code
COPY . .


# Install Playwright and its dependencies
RUN npx playwright install --with-deps

RUN npm run build

# Expose the application port
EXPOSE 3003

# Set the command to run the development server
CMD ["npm", "run", "dev"]
